### ISSUE TITLE
OSE Umbrella

### ISSUE THREAD

**Issue by thymikee** [callstack/haul#356]
This is an umbrella of OSE team to keep track on things want to do:

- [x] Workers (https://github.com/callstack/haul/pull/339) – @zamotany & @Krizzu 
- Webpack 4 migration:
  - [x] create `webpack-next` branch – @thymikee
  - [x] bump the Webpack version & adjust config – @kpsroka
  - [x] ~update loaders & resolvers~ (probably not necessary to change) - @satya164
- [x] Implement new config (#323) – @jukben
- [ ] Speedup Babel transpilation (https://github.com/callstack/haul/issues/353)
  - [ ] add option to not compress cache (https://github.com/babel/babel-loader/pull/574) - @thymikee
  - [ ] don't stringify/parse the babel transform output for cache [PR in progress] - @thymikee
- [ ] Profile and improve performance
- Maintain issue tracker:
  - [x] https://github.com/callstack/haul/issues/349
  - [x] https://github.com/callstack/haul/issues/345
  - [x] https://github.com/callstack/haul/issues/359

**Comment by zamotany** [comment]
What about workers?

**Comment by thymikee** [comment]
It's technically not a strict part of OSE group, but hope we can help somehow. Added now!
