### ISSUE TITLE
Setup meta

### ISSUE THREAD

**Issue by grabbou** [callstack/haul#38]
There's a couple of features we have to implement before open sourcing this repository. 

Here's the list:
- [x] Add `Contributing.md` guide
- [x] Specify issue template
- [x] List all contributors in package.json
- [x] Fix `git` urls in package.json
- [x] Go over closed issues and make sure they are readable

I am not feeling comfortable with early commits that happened to this repository (development, fast iteration, short messages, small issues), but I want to keep list of contributions and history.
